### ISSUE TITLE
Notary flist

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digitalmeX#32]
We need an flist that is able to run the notary gedis actor and the lapis REST layer on top.

**Comment by zaibon** [comment]
@rkhamis please assign this to someone.

**Comment by BolaNasr** [comment]
Notary flist : https://hub.grid.tf/bola_nasr_1/notary_autostart_development.flist 

it's merged flist from : 
startup toml flist : https://hub.grid.tf/bola_nasr_1/notary_startup.flist (Based on)
JumpscaleX flist : https://hub.grid.tf/tf-autobuilder/threefoldtech-jumpscaleX-autostart-development.flist

**Comment by zaibon** [comment]
@BolaNasr where is the code that create these flist please ?

**Comment by BolaNasr** [comment]
@zaibon   i created bash script in flist ( auto build) 
https://github.com/threefoldtech/jumpscaleX/commit/6405c51589d369a6001d0d725f953cf8b3f42d07

and then my startup.toml run this bash file 

startup.toml file 
```toml 
[startup.mystartup]
name = "core.system"

[startup.mystartup.args]
name = "bash"
args = [
    "/sandbox/notary_startup.sh"
]
```
